test1: test1.c ../reader.c
	gcc test1.c ../reader.c -o test1

test2: test2.c ../reader.c ../png_writer.c ../txt_writer.c
	gcc test2.c ../reader.c ../png_writer.c ../txt_writer.c -o test2 -lpng

test3: test3.c ../reader.c ../txt_writer.c ../next_gen.c
	gcc test3.c ../reader.c ../txt_writer.c ../next_gen.c -o test3
