testReader: testReader.c ../reader.c ../generation.c
	gcc testReader.c ../reader.c ../generation.c -o testReader

testTxtWriter: testTxtWriter.c ../txt_writer.c
	gcc testTxtWriter.c ../txt_writer.c -o testTxtWriter

testPngWriter: testPngWriter.c ../png_writer.c ../generation.c
	gcc testPngwriter.c ../png_writer.c ../generation.c -o testPngWriter -lpng

testNextGen: testNextGen.c ../next_gen.c ../generation.c 
	gcc testNextGen.c ../next_gen.c ../generation.c -o testNextGen
